coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

ignore:
  - '**/mocks/mock_*.go'
  - '**/fixtures/*.go'
  - 'e2e/**/*.go'
