coverage:
  status:
    project:
      default:
        informational: true
        target: auto
    patch:
      default:
        only_pulls: true
        target: 70%
        threshold: 0%
ignore:
  - '**/mocks/mock_*.go'
  - '**/fixtures/*.go'
  - 'e2e/**/*.go'
